"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import type { KnowledgeDocument } from "@/server/types";
import { FIELD_DEFINITIONS } from "@/server/competitions/types";
import type { EventDetail, EvidenceInput, FieldPath, RuleBody, RuleField, RuleVersion } from "@/server/competitions/types";
import { ruleApi, RuleApiError } from "./competition-api";
import { RuleFieldEditor } from "./rule-field";
import { RuleSourcePicker, type SourceDetail } from "./rule-source-picker";

type Props = { detail: EventDetail; version: RuleVersion; documents: KnowledgeDocument[]; onSaved: () => Promise<void>; onVersionSaved: (version: RuleVersion) => void; onEditState: (dirty: boolean, busy: boolean) => void };
const groups = [["content", "比赛内容"], ["student", "学生要求"], ["team", "团队与教师"], ["tags", "方向标签 · 维护者建议"], ["school", "学校认定"], ["deadlines", "截止日期"], ["materials", "材料要求"]] as const;
function display(field: RuleField) { const value = field.value; if (value === null) return "未知"; if (Array.isArray(value)) return value.join("、"); if (typeof value === "boolean") return value ? "是" : "否"; if (typeof value === "object") return "precision" in value ? `${value.name} · ${value.value} · ${value.stage}` : `${value.name} · ${value.requirement === "required" ? "必需" : value.requirement === "optional" ? "可选" : "要求未知"} · ${value.stage} · ${value.condition}`; return String(value); }
function completeBody(body: RuleBody): RuleBody { const next = structuredClone(body); FIELD_DEFINITIONS.forEach(item => { next.fields[item.path] ??= { kind: item.kind, value: null, state: "unknown", note: "" }; }); return next; }
export function RuleEditor({ detail, version: initial, documents, onSaved, onVersionSaved, onEditState }: Props) {
  const [version, setVersion] = useState(initial);
  const [body, setBody] = useState<RuleBody>(() => completeBody(initial.body));
  const [evidence, setEvidence] = useState<EvidenceInput[]>(() => structuredClone(initial.evidence));
  const [dirty, setDirty] = useState(false);
  const [busy, setBusy] = useState(false);
  const busyRef = useRef(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [selected, setSelected] = useState<FieldPath | null>("content.summary");
  const [loaded, setLoaded] = useState<Record<string, SourceDetail>>({});
  const [summary, setSummary] = useState<RuleVersion | null>(null);
  const summaryRef = useRef<HTMLDivElement>(null);
  const onLoaded = useCallback((next: Record<string, SourceDetail>) => setLoaded(next), []);
  useEffect(() => { onEditState(dirty, busy || summary !== null); }, [dirty, busy, summary, onEditState]);
  useEffect(() => () => onEditState(false, false), [onEditState]);
  useEffect(() => { if (summary) summaryRef.current?.focus(); }, [summary, busy]);
  function changed() { setDirty(true); setNotice(""); onEditState(true, busyRef.current); }
  function updateField(path: FieldPath, next: RuleField) { setBody(previous => ({ ...previous, fields: { ...previous.fields, [path]: { ...next, state: next.value === null ? "unknown" : previous.fields[path]?.state === "conflict" && next.value === previous.fields[path]?.value && next.kind === previous.fields[path]?.kind ? "conflict" : "unreviewed" } } })); changed(); }
  function revoke(fields: RuleBody["fields"], paths: Set<FieldPath>) { const next = { ...fields }; paths.forEach(path => { const field = next[path]; if (field) next[path] = { ...field, state: field.value === null ? "unknown" : "unreviewed" }; }); return next; }
  function changeEvidence(next: EvidenceInput[]) { const signature = (item: EvidenceInput) => `${item.fieldPath}|${item.documentId}|${item.chunkId}`; const previousKeys = new Set(evidence.map(signature)); const nextKeys = new Set(next.map(signature)); const paths = new Set([...evidence.filter(item => !nextKeys.has(signature(item))), ...next.filter(item => !previousKeys.has(signature(item)))].map(item => item.fieldPath)); setEvidence(next); setBody(previous => ({ ...previous, fields: revoke(previous.fields, paths) })); changed(); }
  function changeSources(next: RuleBody["sources"]) { const ids = new Set(next.map(source => source.documentId)); const changedIds = new Set(body.sources.filter(source => { const replacement = next.find(item => item.documentId === source.documentId); return !replacement || replacement.applicabilityNote !== source.applicabilityNote || replacement.confirmed !== source.confirmed; }).map(source => source.documentId)); const paths = new Set(evidence.filter(item => changedIds.has(item.documentId)).map(item => item.fieldPath)); setEvidence(previous => previous.filter(item => ids.has(item.documentId))); setBody(previous => ({ ...previous, sources: next, fields: revoke(previous.fields, paths) })); changed(); }
  function canConfirm(path: FieldPath, field: RuleField) { return field.value !== null && (path.startsWith("tags.") ? !!field.note.trim() : evidence.some(item => item.fieldPath === path && body.sources.some(source => source.documentId === item.documentId) && documents.some(doc => doc.id === item.documentId) && loaded[item.documentId]?.chunks.some(chunk => chunk.id === item.chunkId))); }
  function confirm(path: FieldPath, field: RuleField) { if (!canConfirm(path, field)) return; setBody(previous => ({ ...previous, fields: { ...previous.fields, [path]: { ...field, state: "confirmed" } } })); changed(); }
  function markConflict(path: FieldPath, field: RuleField) {
    if (field.value === null || !field.note.trim()) return;
    setBody(previous => ({ ...previous, fields: { ...previous.fields, [path]: { ...field, state: "conflict" } } }));
    changed();
  }
  function add(prefix: "deadlines" | "materials") { const itemId = crypto.randomUUID(); const path: FieldPath = `${prefix}.${itemId}`; updateField(path, { kind: prefix === "deadlines" ? "date" : "material", value: prefix === "deadlines" ? { itemId, name: "", stage: detail.event.stage, precision: "date", value: "", timezone: "Asia/Shanghai" } : { itemId, name: "", stage: detail.event.stage, requirement: "unknown", condition: "" }, state: "unreviewed", note: "" }); setSelected(path); }
  function remove(path: FieldPath) { setBody(previous => { const fields = { ...previous.fields }; delete fields[path]; return { ...previous, fields }; }); setEvidence(previous => previous.filter(item => item.fieldPath !== path)); if (selected === path) setSelected(null); changed(); }
  function fail(e: unknown) { setError(e instanceof RuleApiError && e.status === 409 ? `${e.message} 本地编辑已保留。请重新载入后手工核对两个版本，不会自动覆盖。` : e instanceof Error ? e.message : "操作失败，请重试。"); }
  async function saveData() { const result = await ruleApi<{ version: RuleVersion }>(`/api/competitions/versions/${encodeURIComponent(version.id)}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expectedRevision: version.editRevision, body, evidence }) }); setVersion(result.version); onVersionSaved(result.version); setBody(completeBody(result.version.body)); setEvidence(result.version.evidence); setDirty(false); onEditState(false, true); return result.version; }
  async function save(review: boolean) { if (busyRef.current) return; busyRef.current = true; setBusy(true); onEditState(dirty, true); setError(""); try { const saved = await saveData(); setNotice("草稿已保存。"); if (review) setSummary(saved); } catch (e) { fail(e); } finally { busyRef.current = false; setBusy(false); } }
  async function publish() { if (!summary || busyRef.current) return; busyRef.current = true; setBusy(true); setError(""); try { await ruleApi(`/api/competitions/versions/${encodeURIComponent(summary.id)}/publish`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expectedRevision: summary.editRevision }) }); setSummary(null); setDirty(false); onEditState(false, false); await onSaved(); } catch (e) { fail(e); } finally { busyRef.current = false; setBusy(false); } }
  async function reloadLocal() {
    if (busyRef.current || (dirty && !window.confirm("重新载入会放弃本地未保存修改，是否继续？"))) return;
    busyRef.current = true; setBusy(true); onEditState(dirty, true); setError("");
    try { await onSaved(); }
    catch (e) { fail(e); }
    finally { busyRef.current = false; setBusy(false); }
  }
  const locked = busy || summary !== null;
  function field(path: FieldPath, label: string, fallback: RuleField) { const current = body.fields[path] ?? fallback; return <RuleFieldEditor key={path} path={path} label={label} field={current} disabled={locked} selected={selected === path} onSelect={() => setSelected(path)} onChange={next => updateField(path, next)} canConfirm={canConfirm(path, current)} onConfirm={() => confirm(path, current)} onConflict={() => markConflict(path, current)} onDelete={path.startsWith("deadlines.") || path.startsWith("materials.") ? () => remove(path) : undefined} />; }
  const label = (path: string) => FIELD_DEFINITIONS.find(item => item.path === path)?.label ?? (path.startsWith("deadlines.") ? "截止事项" : "材料要求");
  return <section className="rule-editor" aria-label="编辑规则草稿"><div className="rule-editor-toolbar"><span>{dirty ? "有未保存修改" : "草稿已保存"} · 修订 {version.editRevision}</span><div className="competition-actions"><button className="outline small" disabled={locked} onClick={() => save(false)}>{busy ? "处理中…" : "保存草稿"}</button><button className="primary small" disabled={locked} onClick={() => save(true)}>保存并审阅发布</button><button className="text-button" disabled={locked} onClick={reloadLocal}>重新载入</button></div></div>{error && !summary && <p className="alert error" role="alert">{error}</p>}{notice && <p className="alert success" role="status">{notice}</p>}<div className="rule-editor-layout"><div className="rule-edit-groups">{groups.map(([prefix, heading]) => { const dynamic = Object.keys(body.fields).filter(path => path.startsWith(`${prefix}.`)) as FieldPath[]; return <section key={prefix}><h3>{heading}</h3>{FIELD_DEFINITIONS.filter(item => item.path.startsWith(`${prefix}.`)).map(item => field(item.path, item.label, { kind: item.kind, value: null, state: "unknown", note: "" }))}{(prefix === "deadlines" || prefix === "materials") && <>{dynamic.map(path => field(path, label(path), body.fields[path]!))}<button className="outline small" disabled={locked || dynamic.length >= 20} onClick={() => add(prefix)}>添加{prefix === "deadlines" ? "截止事项" : "材料"}（{dynamic.length}/20）</button></>}</section>; })}</div><RuleSourcePicker documents={documents} event={detail.event} sources={body.sources} evidence={evidence} fieldPath={selected} disabled={locked} onSourcesChange={changeSources} onEvidenceChange={changeEvidence} onLoaded={onLoaded} /></div>
  {summary && <div className="modal-backdrop"><div className="modal rule-publish-summary" role="dialog" aria-modal="true" aria-labelledby="rule-publish-title" tabIndex={-1} ref={summaryRef} onKeyDown={e => { if (e.key === "Escape" && !busy && e.currentTarget.contains(document.activeElement)) setSummary(null); if (e.key === "Tab") { const buttons = Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>("button:not(:disabled)")); const first = buttons[0]; const last = buttons.at(-1); if (!first) { e.preventDefault(); e.currentTarget.focus(); return; } if (e.shiftKey && (document.activeElement === first || document.activeElement === e.currentTarget)) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } } }}>{error && <p className="alert error" role="alert">{error}</p>}<h2 id="rule-publish-title">核对后明确发布 v{summary.version}</h2><p>草稿已保存。发布表示规则资料审核完成，不代表参赛资格批准；服务端会校验全部字段与来源。</p>{["confirmed", "unknown", "unreviewed", "conflict"].map(state => { const entries = FIELD_DEFINITIONS.map(item => [item.path, summary.body.fields[item.path] ?? { kind: item.kind, value: null, state: "unknown", note: "" }] as const).concat(Object.entries(summary.body.fields).filter(([path]) => /^(deadlines|materials)\./.test(path)).map(([path, value]) => [path as typeof FIELD_DEFINITIONS[number]["path"], value!] as const)); return <section key={state}><h3>{{ confirmed: "全部已确认项", unknown: "全部未知项", unreviewed: "待确认项", conflict: "冲突项" }[state]}</h3><ul>{entries.filter(([, value]) => value.state === state).map(([path, value]) => <li key={path}><strong>{label(path)}</strong>：{display(value)}{value.note && ` · 说明：${value.note}`}</li>)}</ul></section>; })}<h3>全部适用来源</h3>{summary.body.sources.map(source => <p key={source.documentId}><strong>{documents.find(doc => doc.id === source.documentId)?.title ?? "原文不可用"}</strong> · {source.confirmed ? "已核对" : "未确认"}<br />{source.applicabilityNote || "适用说明未填写"}</p>)}{!summary.body.sources.length && <p>暂无来源，不能发布。</p>}<div className="competition-actions"><button className="outline" disabled={busy} onClick={() => setSummary(null)}>返回继续核对</button><button className="primary" disabled={busy} onClick={publish}>{busy ? "发布中…" : "确认上述内容并发布"}</button></div></div></div>}
  </section>;
}
